### ISSUE TITLE
The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

### ISSUE THREAD

**Issue by GuckTubeYT** [Mempler/GTItemBindings.Generator#1]
C:\Users\GuckTubeYT\Desktop\ITEMSDAT\Growtopia_ItemsDecoder-master\GTItemBindings.Generator-master\GTItemBindings.Generator\GTItemBindings.Generator.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\GuckTubeYT\Desktop\ITEMSDAT\Growtopia_ItemsDecoder-master\GTItemBindings.Generator-master\GTItemBindings.Generator\GTItemBindings.Generator.csproj

C:\Users\GuckTubeYT\Desktop\ITEMSDAT\Growtopia_ItemsDecoder-master\GTItemBindings.Generator-master\GTItemBindings.Generated\GTItemBindings.Generated.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\GuckTubeYT\Desktop\ITEMSDAT\Growtopia_ItemsDecoder-master\GTItemBindings.Generator-master\GTItemBindings.Generated\GTItemBindings.Generated.csproj

how to fix this

**Comment by GuckTubeYT** [comment]
hey

**Comment by Mempler** [comment]
requires .net core 3.1 `https://dotnet.microsoft.com/download` + .net core for Visual Studio 2019

**Comment by GuckTubeYT** [comment]
Ok

**Comment by GuckTubeYT** [comment]
> 
> 
> requires .net core 3.1 `https://dotnet.microsoft.com/download` + .net core for Visual Studio 2019

runtime or sdk?

**Comment by GuckTubeYT** [comment]
still bruh

**Comment by Mempler** [comment]
SDK obviously, please. If you don't know how to use .net, you can't use this as this Library requires you a lot of C# knowledge. Thanks. I won't help with noob questions as those are not related with this Project.

**Comment by GuckTubeYT** [comment]
> 
> 
> SDK obviously, please. If you don't know how to use .net, you can't use this as this Library requires you a lot of C# knowledge. Thanks. I won't help with noob questions as those are not related with this Project.

when i use sdk version, but it still error

**Comment by Mempler** [comment]
try using the dotnet CLI provided by .Net SDK 3.1

**Comment by GuckTubeYT** [comment]
> 
> 
> try using the dotnet CLI provided by .Net SDK 3.1

ok

**Comment by GuckTubeYT** [comment]
btw, this is can encode?

**Comment by Mempler** [comment]
Yes, but that requires you to learn C# as you have to create your own project and get all items using reflection.
Then you have to write The ItemsDb version(11) ontop && Item Count.
After that you can simply use `item.Pack`
Like i said before, this repository requires ADVANCED C# knowledge my lil Turkish boy. If you don't have it, feel free to close this issue and never come back.

**Comment by Mempler** [comment]
Closing since there is not further communication after 7 days.
